CREATE TABLE EMP_EMPRESA (
    ID                              BIGINT AUTO_INCREMENT NOT NULL,
    EMP_NM_CPNJ_BASE                VARCHAR(8)            NULL,
    EMP_DS_RAZAO_SOCIAL             VARCHAR(255)          NULL,
    EMP_CD_NATUREZA_JURIDICA        VARCHAR(255)          NULL,
    EMP_DS_QUALIFICACAO_RESPONSAVEL VARCHAR(255)          NULL,
    EMP_VL_CAPITAL_SOCIAL           DOUBLE                NULL,
    EMP_CD_PORTE_EMPRESA            VARCHAR(255)          NULL,
    EMP_DS_ENTE_FEDERATIVO          VARCHAR(255)          NULL,
    CONSTRAINT PK_EMP_EMPRESA PRIMARY KEY (ID)
);